# Generated by Django 5.1.5 on 2025-01-27 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CPU', 'Computador'), ('MONITOR', 'Monitor'), ('TABLET', 'Tablet'), ('MOVIL', 'Celular')], max_length=10)),
                ('estado', models.CharField(blank=True, choices=[('REPARAR', 'En reparación'), ('BUENO', 'Buen estado'), ('PERDIDO', 'Perdido/robado'), ('COMPRADO', 'Comprado'), ('MALO', 'Mal estado')], max_length=10, null=True)),
                ('marca', models.CharField(choices=[('DELL', 'Dell'), ('HP', 'HP'), ('LENOVO', 'Lenovo'), ('APPLE', 'Apple'), ('SAMSUNG', 'Samsung')], max_length=10)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('regimen', models.CharField(blank=True, choices=[('ECCC', 'ECCC'), ('ECOL', 'ECOL'), ('CNC', 'CNC')], max_length=10, null=True)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50, unique=True)),
                ('placa_cu', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo_disco_duro', models.CharField(blank=True, choices=[('HDD', 'HDD (Disco Duro Mecánico)'), ('SSD', 'SSD (Disco de Estado Sólido)'), ('HYBRID', 'Híbrido (HDD + SSD)')], max_length=10, null=True)),
                ('capacidad_disco_duro', models.CharField(blank=True, choices=[('120GB', '120 GB'), ('250GB', '250 GB'), ('500GB', '500 GB'), ('1TB', '1 TB'), ('2TB', '2 TB'), ('4TB', '4 TB'), ('8TB', '8 TB')], max_length=10, null=True)),
                ('tipo_memoria_ram', models.CharField(blank=True, choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('LPDDR4', 'LPDDR4'), ('LPDDR5', 'LPDDR5')], max_length=10, null=True)),
                ('capacidad_memoria_ram', models.CharField(blank=True, choices=[('2GB', '2 GB'), ('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB')], max_length=10, null=True)),
                ('ubicacion', models.CharField(blank=True, choices=[('CASA', 'Casa'), ('CLIENTE', 'Cliente'), ('SEDE', 'Sede'), ('OTRO', 'Otro')], max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Estadoproveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estado de Proveedor',
                'verbose_name_plural': 'Estados de Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cambios', models.TextField()),
                ('tipo_cambio', models.CharField(default='Movimiento registrado', max_length=100)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_origen', models.CharField(max_length=50)),
                ('ubicacion_destino', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.dispositivo')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='posicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='dispositivos.posicion'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.sede'),
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_analitico', models.TextField(blank=True, null=True)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispositivos.sede')),
            ],
            options={
                'verbose_name': 'Servicios',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
