# Generated by Django 5.1.5 on 2025-01-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicion',
            name='piso',
            field=models.CharField(choices=[('PISO1', 'Piso 1'), ('PISO2', 'Piso 2'), ('PISO3', 'Piso 3'), ('PISO4', 'Piso 4')], default=0, max_length=5),
            preserve_default=False,
        ),
    ]
