# Generated by Django 5.1.5 on 2025-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('TABLET', 'Tablet'), ('MOVIL', 'Celular')], max_length=10),
        ),
    ]
