# Generated by Django 5.1.5 on 2025-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='sede',
        ),
        migrations.AddField(
            model_name='servicios',
            name='sedes',
            field=models.ManyToManyField(related_name='servicios', to='dispositivos.sede'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='serial',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
