# Generated by Django 5.1.5 on 2025-01-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roluser',
            name='sedes',
            field=models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='dispositivos.sede'),
        ),
    ]
