# Generated by Django 5.1.5 on 2025-01-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='esta_ocupada',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='capacidad_disco_duro',
            field=models.CharField(blank=True, choices=[('120GB', '120 GB'), ('250GB', '250 GB'), ('500GB', '500 GB'), ('1TB', '1 TB'), ('2TB', '2 TB'), ('4TB', '4 TB'), ('8TB', '8 TB')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='capacidad_memoria_ram',
            field=models.CharField(blank=True, choices=[('2GB', '2 GB'), ('4GB', '4 GB'), ('8GB', '8 GB'), ('16GB', '16 GB'), ('32GB', '32 GB'), ('64GB', '64 GB')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='estado',
            field=models.CharField(blank=True, choices=[('REPARAR', 'En reparación'), ('BUENO', 'Buen estado'), ('PERDIDO', 'Perdido/robado'), ('COMPRADO', 'Comprado'), ('MALO', 'Mal estado')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='placa_cu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='razon_social',
            field=models.CharField(blank=True, choices=[('CNC', 'CNC'), ('ECCC', 'ECCC'), ('ECOL', 'ECOL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_disco_duro',
            field=models.CharField(blank=True, choices=[('HDD', 'HDD (Disco Duro Mecánico)'), ('SSD', 'SSD (Disco de Estado Sólido)'), ('HYBRID', 'Híbrido (HDD + SSD)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='tipo_memoria_ram',
            field=models.CharField(blank=True, choices=[('DDR', 'DDR'), ('DDR2', 'DDR2'), ('DDR3', 'DDR3'), ('DDR4', 'DDR4'), ('LPDDR4', 'LPDDR4'), ('LPDDR5', 'LPDDR5')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(choices=[('DELL', 'Dell'), ('HP', 'HP'), ('LENOVO', 'Lenovo'), ('APPLE', 'Apple'), ('SAMSUNG', 'Samsung')], max_length=10),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
