# Generated by Django 5.1.5 on 2025-02-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_alter_posicion_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicion',
            name='color',
            field=models.CharField(choices=[('530001', '#0094FF'), ('530013', '#00FF00'), ('530014', '#FF9900'), ('152001', '#9900FF'), ('320026', '#6600CC'), ('221003', '#FFD700'), ('390001', '#008080'), ('153001', '#FF66B2'), ('269001', '#FF0000'), ('186020', '#FF4500'), ('Desarrollo', '#FF0000'), ('Soporte', '#8B0000'), ('Selección', '#808000'), ('Leroy Merli', '#8A2BE2'), ('default', 'transparent')], default='transparent', max_length=20),
        ),
    ]
