# Generated by Django 5.1.5 on 2025-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_roluser_sedes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
