# Generated by Django 5.1.5 on 2025-01-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_remove_posicion_esta_ocupada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_analitico', models.TextField(blank=True, null=True)),
                ('sede', models.CharField(max_length=100)),
            ],
        ),
    ]
