# Generated by Django 5.1.5 on 2025-03-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_alter_posicion_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicion',
            old_name='descripcion',
            new_name='detalles',
        ),
        migrations.RenameField(
            model_name='posicion',
            old_name='coordenada_x',
            new_name='fila',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='posicion',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='coordenada_y',
        ),
        migrations.AddField(
            model_name='posicion',
            name='borde',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='bordeDetalle',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='posicion',
            name='bordeDoble',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posicion',
            name='colorFuente',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='posicion',
            name='colorOriginal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='columna',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posicion',
            name='dispositivos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posicion',
            name='mergedCells',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='posicion',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='usuario_asignado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('inactivo', 'Inactivo')], default='disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='piso',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='sede',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='servicio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
